### PR TITLE
[debugger] Windows support + `process-drawable` + `joint`

### PR DESCRIPTION
**Pull request by ManDude**

### CODE REVIEW

**Comment by xTVaser** [comment]
Looks like these two files havn't been added to the reference tests

**Review by water111 — APPROVED** [review]
mutex fixes look good, thanks.  This just needs to have merge conflicts resolved (sorry, I think I did these in a bad order?)

**Comment by water111** [comment]
merged in https://github.com/water111/jak-project/pull/953

**Comment by ManDude** [comment]
Awesome, thanks.

**Pull request closed without merging**
