### PR TITLE
decomp: `navigate-h` partially

### PR DESCRIPTION
**Pull request by xTVaser**
Another partially finished header, I'm _really_ interested in what type `root` is on `process-drawable`, that's the main blocker here.

### CODE REVIEW

**Comment by ManDude** [comment]
Where is it used?

**Comment by ManDude** [comment]
Pretty sure it's a `process`, or a child of it (another `process-drawable`)

**Comment by water111** [comment]
Based on this code in `ja-post`, I suspect it's at least sometimes a `collide-shape`.
```
    lw t9, type-type?(s7)     ;; (set! t9 type-type?)[34]
    lwu v1, 108(s6)           ;; (set! v1 (l.wu (+ s6 108)))[35]
    lwu a0, -4(v1)            ;; (set! a0 (l.wu (+ v1 -4)))[36]
    lw a1, collide-shape(s7)  ;; (set! a1 collide-shape)[37]
    jalr ra, t9               ;; (call!)[38]
    sll v0, ra, 0
    ```

**Comment by xTVaser** [comment]
navigate-h finished here https://github.com/water111/jak-project/pull/592

**Pull request closed without merging**
