### PR TITLE
spdlog implementation

### PR DESCRIPTION
**Pull request by doctashay**

### CODE REVIEW

**Comment by xTVaser** [comment]
Associated Issue - https://github.com/water111/jak-project/issues/20

**Comment by water111** [comment]
It looks like there's still some sort of CMake error going on, I get this error on my computer and on github actions:
```
/home/runner/work/jak-project/jak-project/./third-party/spdlog/include/spdlog/details/registry-inl.h:20:10: fatal error: spdlog/sinks/ansicolor_sink.h: No such file or directory
 #include <spdlog/sinks/ansicolor_sink.h>```

**Comment by doctaweed** [comment]
That error also came up in tests that failed. I’m not quite sure why it can’t find these headers on Linux, they are definitely present. Will take a closer look at CMake configuration today.

**Comment by doctashay** [comment]
Going to restart this PR today.

**Pull request closed without merging**
